### ISSUE TITLE
j2html maven dependencies

### ISSUE THREAD

**Issue by dvasunin** [tipsy/j2html#11]
First, I'd like to thank you for useful project. I started using it for creating html reports and found it very handy. However when I added j2html as a dependency to my project the size of final war-file has been almost doubled from 10 Mb to 18 Mb. I found that j2html hooked up ant, ant-launcher, guava, closure-compiler, .. and many others jar files. I wonder if they all are needed for run-time? If not, please correct the dependency list in the .pom file to set correct scope for them.
Best regards,

**Comment by tipsy** [comment]
You're very welcome @dvasunin! I only have three dependencies: JUnit, commons-lang3 and closure-compiler. I could set JUnit to scope:test, but the other two are needed. It's probably closure-compiler pulling in all those other dependencies (?).
If you create a pull-request that excludes unneeded dependencies I would be happy to merge it, but version 0.5.0 only had JUnit, maybe you can just it instead? The changes from 0.5.0 to 0.7 are described here: http://j2html.com/news.html#j2html-0.7-released. It's basically just Java 7 support + a file-reading api.
