### ISSUE TITLE
HTML encoding

### ISSUE THREAD

**Issue by Ksoso** [tipsy/j2html#12]
Hi, 
First of all, thanks for great work with easy to handle java library.

I got problem, i can't render euro money (€) sign with `withText()` method. It is even possible to put into tags some special characters ?

**Comment by tipsy** [comment]
Hi @Ksoso, which version are you using? 
0.5.0 had a very naive escaping method, but 0.7 uses Apache Commons. You can always use with(unsafeHtml(("£")) to avoid escaping altogether.

**Comment by Ksoso** [comment]
It's working great, thanks.
