### ISSUE TITLE
Changing HTML at run time

### ISSUE THREAD

**Issue by genericjohndoe** [tipsy/j2html#120]
Would you recommend I'd use this library in an application that allows users to create HTML documents and automatically re-renders them as changes are made?

**Comment by tipsy** [comment]
I would normally recommend something like vue.js for that. Can you elaborate on the use case and your constraints?

**Comment by genericjohndoe** [comment]
I am working on an android application where users can create content like the blog post seen on sites like blogger. In order to generate the type of look that I want for the posts HTML has to be generated dynamically as the user types and adds in media (images, videos, and gifs).

**Comment by tipsy** [comment]
If you have all the user input as a Java structure, then using j2html for this should be okay.
