### ISSUE TITLE
Dont use j2html if you use a CSS framework such as Bootstrap. 

### ISSUE THREAD

**Issue by ijabz** [tipsy/j2html#122]
In front page it says under _Please don't use j2html if_:

> 

> You use a CSS framework such as Bootstrap. We tried to use it for this site, it was a nightmare.

Why not, I have only  just noticed that comment after redoing my webapp and my website with j2html and Bootstrap and didnt have any Bootstrap related problems. 

I think this line should be removed from tutorial, or explaination given.

**Comment by tipsy** [comment]
I will rewrite it.

**Comment by tipsy** [comment]
I rewrote it to

<blockquote>
<h2>Be careful about using j2html if:</h2>
<ul>
<li>...</li>
<li>You use a CSS framework which relies on a lot of copy pasting HTML from docs. You'll have to translate these snippets to j2html</li>
</ul>
</blockquote>

**Comment by zenkio** [comment]
> In front page it says under _Please don't use j2html if_:
> 
> > 
> 
> > You use a CSS framework such as Bootstrap. We tried to use it for this site, it was a nightmare.
> 
> Why not, I have only just noticed that comment after redoing my webapp and my website with j2html and Bootstrap and didnt have any Bootstrap related problems.
> 
> I think this line should be removed from tutorial, or explaination given.

If it is possible to share some Technic with j2html and bootstrap?
