### ISSUE TITLE
renderFormatted() causes unwanted whitespace to be rendered by browser

### ISSUE THREAD

**Issue by dwalluck** [tipsy/j2html#125]
The `renderFormatted()` method causes additional whitespace to be rendered by the browser. This applies to any tag that is a text container. It should probably be the case that tags with text content hug that content.

For example,

```
    <span>
        te
    </span>
    st
   <span>
       test
   </span>
```

would be rendered as

```
    <span>te</span>st
    <span>test</span>
```

 having the opening and closing tags "hug" their content.

Otherwise, the browser will insert an additional spaces between one container tag and the other making it impossible to render them without space.

The HTML standard <https://www.w3.org/TR/html401/appendix/notes.html#notes-line-breaks> seems to indicate that the browser should render these two the same, but I tested with both in Google Chrome and Mozilla Firefox with the same results of an extra space.

This is complicated by the fact that if I try to use something like `text("te"), text("st")` it also adds newlines and indents even though this is just plain text in this case. Is there already a workaround to get these rendered right next to one another? Note that I cannot write `text("test")`. This was just an example. In reality, they are separate tags so they cannot be combined.

**Comment by tipsy** [comment]
@dwalluck If you create a PR for this I would be happy to merge it.
