### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by tmarcoe** [tipsy/j2html#126]
I like your java library. I'm using it to generate html formatted emails. What I am trying to do is show a sales receipt with a total at the bottom. I have everything except a way to total up the price and tax for each line item so I can put the grand total at the bottom of the page. Is there any documentation that I am missing?

**Comment by esiqveland** [comment]
That should be computed by caller and is not the job of an html rendering library.

**Comment by tmarcoe** [comment]
Thank you. I do have other questions, but let me see if I can figure these
out for myself first. I know I can figure out at least some of them.

**Comment by tipsy** [comment]
While I agree that the documentation could use some improvement, the functionality you're describing is outside of the scope of the project. 

j2html is strictly a rendering library, it only cares about transforming Java code to HTML. Any business logic will have to be implemented by the end users.
