### ISSUE TITLE
Tag font not exist

### ISSUE THREAD

**Issue by isvaldo** [tipsy/j2html#13]
I'd like something like that
<font color='#FFFFFF'>data</font>"

for html email purpose

**Comment by isvaldo** [comment]
solved 
emptyTag("font")
                                        .attr("color","#FFFFFF").withContent("ID")

**Comment by isvaldo** [comment]
Ops:
I get 
tr><td bgcolor="#00000" align="center" valign="top"><b><font color="#FFFFFF" content="ID"></b></td></tr>

But i want 

<font color="#FFFFFF" content="ID">HERE CONTENT</font>

**Comment by tipsy** [comment]
Font is not a valid HTML5 tag, is there any specific reason you want to use it?

**Comment by tipsy** [comment]
```tag("font").attr("color", "#FFFFFF").withContent("ID").with(text("Some text"))```
will output:
```<font color="#FFFFFF" content="ID">Some text</font>```

**Comment by isvaldo** [comment]
Oh, thanks
http://webdesign.tutsplus.com/articles/build-an-html-email-template-from-scratch--webdesign-12770

**Comment by tipsy** [comment]
Ah, email. Good luck :)
