### ISSUE TITLE
The setValue method in Attribute does not escape the value

### ISSUE THREAD

**Issue by LukasKarsten** [tipsy/j2html#135]
When overriding an attribute through the 'setAttribute' method in the Tag class the old attribute is updated through the 'setValue' method, however this method does not escape the value and so code like this:
```Java
p().withClass("foo").withClass("bar\"baz")
```
will produce the following html code:
```html
<p class="bar"baz"></p>
```
which obviously is not valid.

**Comment by sembler** [comment]
Looks like this was fixed by #162.  Closing this issue.
