### ISSUE TITLE
Unable to read files from directories other that /src/main/resources

### ISSUE THREAD

**Issue by austinlostinboston** [tipsy/j2html#14]
I ran into this issue today when I was trying to add a css file that resided in my java project that I'm using j2html in. I was trying to do this using the following code.

`Tag css = styleWithInlineFile("style.css");`

However, css was continually being set to `null`. Looking through the code, I think I see why. In `InlineStaticResource.java`, when the `getFileAsString` method is called, the file path is constructed using `InlineStaticResource.class.getResource(path)`. However, I believe this method is constructing and incorrect file path. From how I understand the line above to work, it's basically only looking in the directory of `InlineStaticResource.java` and below. Which means j2html effectively can't see any files outside of this directory.

I'm using java 8 inside eclipse along with Maven.

Please let me know if my understanding is correct or if I should be able to add a css file given the current code.

Thanks!

**Comment by tipsy** [comment]
You should be able to read static resources from ```src/main/resources```. Where is your stylesheet located?

**Comment by austinlostinboston** [comment]
My css file is in the root directory of the java project. An example path to the file is `pathToProject/projectName/style.css`. Also, I'm able to use `getClass().getResource("style.css");` to get the absolute path of the file. Doesn't this mean my css file is in `src/main/resources`?

**Comment by tipsy** [comment]
Seems you're not following the [Maven Standard Directory Layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). I'm so used to this layout that I never tested it with a different one. Would you like to fork the project and take a stab at making it work for your use-case?

**Comment by austinlostinboston** [comment]
Thanks for pointing this out. While I've been using java on and off for the past few years, I am quite new to maven. Once I changed the file structure to abide by Maven's standard, everything worked as intended.
Once I get some free time, I'll fork the project and try and generalize that portion of the code to work with projects that might not follow the Maven standard.

Thanks for help tipsy, I really appreciate!

**Comment by tipsy** [comment]
Glad to hear it works now. I've added a bug label and will keep the issue open.

**Comment by mrtinkz** [comment]
I was going through the same problem, since all we need is the string from the file, how about adding two more methods which takes string as parameter instead of the a file path, this should for now temporarily fix the problem until a permanent solution. Also if you do not like the idea of passing the string, we can also pass an input stream, let me know if you have more suggestions, I can fork and make those changes, thank you. By the way this is a very good library :+1: .

```
 public static ContainerTag styleWithInlineFile(String style)      { return InlineStaticResource.get(path, InlineStaticResource.TargetFormat.CSS); }
    public static ContainerTag scriptWithInlineFile(String js)     { return InlineStaticResource.get(path, InlineStaticResource.TargetFormat.JS); }
    public static ContainerTag styleWithInlineFile_min(String style)  { return InlineStaticResource.get(path, InlineStaticResource.TargetFormat.CSS_MIN); }
    public static ContainerTag scriptWithInlineFile_min(String js) { return InlineStaticResource.get(path, InlineStaticResource.TargetFormat.JS_MIN); }
```

**Comment by tipsy** [comment]
@mrtinkz, @austinlostinboston What do you think about #50 ?

**Comment by mrtinkz** [comment]
@tipsy thanks for the fix, looks good!

**Comment by tipsy** [comment]
Try it out in 

```xml
<dependency>
    <groupId>com.j2html</groupId>
    <artifactId>j2html</artifactId>
    <version>0.99</version>
</dependency>
```

if you haven't :)
