### ISSUE TITLE
style() tag html escapes the css code 

### ISSUE THREAD

**Issue by tfbroner** [tipsy/j2html#140]
When I do something like : 
`html(head(title("Test"), style(".testnav>a {}"))).render();`
it ends up escaped like :
`<html><head><title>Test</title><style>.testnav&gt;a {}</style></head></html>`
which makes it invalid css code.

Any ideas as to what I'm doing wrong ?

**Comment by tipsy** [comment]
You could try `.rawHtml("<style>...</style>")`

**Comment by tfbroner** [comment]
Thanks, 
I used rawHtml inside the style tag and it worked as well.

**Comment by sembler** [comment]
PR #181 has been merged.  Now any String parameters for the `TagCreator.script(...)` or `TagCreator.style(...)` methods will be treated as unescaped text.
