### ISSUE TITLE
Java 9 modularization support

### ISSUE THREAD

**Issue by mkpaz** [tipsy/j2html#142]
Please, consider adding `module-info.java` or `Automatic-Module-Name` (http://branchandbound.net/blog/java/2017/12/automatic-module-name) at least. The absence these really hurts projects that use jlink to build runtime images.

**Comment by tipsy** [comment]
Thanks @mkpaz. Could you submit a PR?

**Comment by sembler** [comment]
#183 has been merged and `Automatic-Module-Name` is now included in the manifest.
