### ISSUE TITLE
 Feature request | SVG Support

### ISSUE THREAD

**Issue by Azmechatech** [tipsy/j2html#143]
Support to SVG tag is missing.  it will be great if you can have it added.

**Comment by tipsy** [comment]
SVG has its own attribute set, do you mean support for all of it, or just the tag itself?

**Comment by Azmechatech** [comment]
Just the tag itself. Rest I hope I can add via  .attr().

**Comment by tipsy** [comment]
Can you use `tag("SVG")` ?

**Comment by Azmechatech** [comment]
Oh yes,  I didn't think about it.
