### ISSUE TITLE
Refactor Tag classes to avoid code duplication

### ISSUE THREAD

**Issue by tipsy** [tipsy/j2html#17]
Currently ContainerTag and EmptyTag share the same 40 convenience methods, but they're manually included in each class. Attempts at refactoring this have been unsuccessful, as I can't seem to find a way to keep the type-information intact (this is important for the fluent-api chaining). 

For example, if I move them to Tag (the abstract class they both extend), and do

```div().withClass("class").withText()```, I run into problems, because ```withText()``` should be available for ContainerTag objects, but not EmptyTag objects.

I'm sure there's a way though... any thoughts?

**Comment by snaketl** [comment]
Hi!
I think I could refactor this situation using generics.
This weekend I'll work on this and I'll send you a PR to discuss.

**Comment by tipsy** [comment]
Cool, looking forward to it!

**Comment by snaketl** [comment]
Take a look on this [commit](https://github.com/snaketl/j2html/commit/9405c2d5f5ea4a209a2becad7a9d529264ae8695) and please tell me what do you think about it.

**Comment by tipsy** [comment]
Ended up with [this](https://github.com/tipsy/j2html/commit/2beb4e903e71c224d1643add961fcb5fd1f8152a). Thanks for your help @snaketl, please let me know if there are any problems with the commit.

**Comment by snaketl** [comment]
I'm glad to help you!
