### ISSUE TITLE
[Feature Request] XML to j2html and then allow traverse

### ISSUE THREAD

**Issue by Azmechatech** [tipsy/j2html#170]
Requesting a feature to convert a given XML to the container tags and then allow navigation through the generated container tags.

**Comment by pointbazaar** [comment]
not sure what you are talking about specifically, but 

https://github.com/rupert-madden-abbott/j2html-generator
claims to be able to convert HTML into j2html code.

if you want an XML parser, there are probably plenty good ones out there.

just mention me if you meant something else.
