### ISSUE TITLE
Maintainer wanted !

### ISSUE THREAD

**Issue by tipsy** [tipsy/j2html#171]

**Comment by RottenLemons** [comment]
Hello Tipsy. 
I am Rotten_Lemons and I would like to be the maintainer of your project. I am a high school student who has experience on both HTML and Java and I also know the usefulness of your project. I hope to help maintain this project by ironing out bugs and adding new features. However, before I maintain the project, I hope you go through firstly with me about its goal, intention and antthing you do not want to do as I do not want to stray from the direction you made this projects towards and also to maybe help understand certain parts of the code if I do not. I hope you pick me as the maintainer.
Thank you.

**Comment by jpomykala** [comment]
Is there are any requirements? What are the main responsibilities? I have a few open source projects:

- https://github.com/jpomykala/spring-higher-order-components - useful ready to use components for Spring
- https://github.com/simplelocalize/simplelocalize-cli CLI for maintaining translations (works in Java and with Java property files)
- https://github.com/jpomykala/awesome-i18n -  i18n resources 

If you think I can handle it, then I'm interested in being a maintainer. 👍

**Comment by sembler** [comment]
Since comments are scarce I'll throw my name into the pot as well.  I work as a contractor and have made use of the j2html library in three different projects over the past several years, including currently maintained projects.  I've been interested in contributing more to the OSS community, and this seems like a nice opportunity to do so.  Most of my prior contributions have been small patches to projects like Flyway and Apache commons-vfs2.

For j2html, most of the currently opened issues don't seem like they would be excessively demanding to fix, but they do lead to questions about what your vision is for the future of j2html.  How committed were you towards compatibility?  Did you have more features envisioned, or intent on deprecating anything?  I ask so that this project could move forward with some amount of continuity.

**Comment by tipsy** [comment]
@RottenLemons Thank you for your interest, but unfortunately you are a bit too inexperienced.

@jpomykala There are no requirements, you can't possibly do a worse job then what I'm doing now (nothing). The main responsibilities is cleaning up the current master branch and getting a release out, and then merging PRs and making any changes you see fit really. Have you used the library before? I think it's a huge benefit it the new maintainer is an active user.

@sembler You sound like a perfect match. One of the main problems is that I don't have a vision for the future of j2html, I haven't used it in something like four years. I made it for a very specific task I had to solve, but it's not a good fit for any of my current projects. There was an effort to introduce more type-safety to the project recently, but I'm not sure how far along it got. We need to clean up the master branch and get a new 1.x version out, then think about what 2.x should be (if there should be a 2.x...?)

**Comment by jpomykala** [comment]
@tipsy Hey, thanks for the response. I think that @sembler would fit better for the position. I personally used the library many times, mostly to create simple e-mail templates on a backend. It would be a huge loss for the Java community, if this project would become unmaintained. Anyway, I'm ready to help if needed.

**Comment by sembler** [comment]
Thank you for your support.  I understand the difficulty of envisioning a way forward after a long absence.  Cleaning up 1.x as you suggest would be a great way to ease into the project.  I'll do a deep-dive into the code and look at how to prioritize issues with the time I have.  Was there anything you remember wanting to do that wasn't documented?

**Comment by tipsy** [comment]
> Was there anything you remember wanting to do that wasn't documented?

There have been efforts to improve type-safety by having each tag-type only allow certain children, but nothing else comes to mind.

**Comment by tipsy** [comment]
>  I'll do a deep-dive into the code and look at how to prioritize issues with the time I have.

Sounds great. I'll give you write access after a few PRs :)

**Comment by obecker** [comment]
Regarding type safety - see the recent discussion here: https://github.com/tipsy/j2html/issues/138#issuecomment-825398029

**Comment by tipsy** [comment]
I've made a new issue for discussing the future of the project: https://github.com/tipsy/j2html/issues/172

**Comment by Tudor44** [comment]
Hello ,

I will try to add this library in my project. I have some hand-written stuff for create some html for prepare and send report mail. I consider to rewriting this part. After I m here for improve the codebase too.

**Comment by tipsy** [comment]
I can see work is being done, you guys are great! I will close the issue now :)
