### ISSUE TITLE
Remove manual HtmlTag class

### ISSUE THREAD

**Issue by obecker** [tipsy/j2html#185]
I would propose to remove the specialized `HtmlTag` class (and also `HeadTag` and `BodyTag`) and just let them be generated like other `ContainerTag` classes.

 - the current change is not compatible to previous versions of j2html, i.e.
   `ContainerTag html = html(body(h1("Hello, world!")));`
   doesn't compile anymore (`HtmlTag` is not a `ContainerTag`)
 - it is not possible to add attributes _before_ the children (as you would do in HTML itself), i.e.
   `html().withLang("en").with(body(h1("Hello, world!")));`
   doesn't compile anymore, the attributes need to be moved to the end, resulting in
   `html(body(h1("Hello, world!"))).withLang("en")`
   which is for real world scenarios impractical
 - the class introduces extra code that needs to be maintained (for example it needs its own `render` method implementation), which is IMHO somewhat error-prone (for example the first version simply forgot to render the attributes - see https://github.com/tipsy/j2html/issues/138#issuecomment-822171574 )
 - I don't see the benefit, as it would be perfectly legal to omit the `body` tag and create HTML like this
   `html(h1("Hello, world!"))`
   (see https://html.spec.whatwg.org/#syntax-tag-omission )
 - finally, it is not really consistent, I mean why do we have such strict constraints for the `html` element, but not for other elements with a comparable strict content model, for example `ul`, `ol`, `dl`, or `tr`?

Summarized: the above disadvantages outweight the (small and questionable) advantage of enforcing a correct content model for the `html` element , so we should replace the manual version of this class with the corresponding generated version.

**Comment by sembler** [comment]
I like the idea, and you've listed good reasons to do this.  Since it is a change that risks breaking user code I'd like to keep this as an item for version 2.

**Comment by sembler** [comment]
After reviewing the commit history, yes we should do this before the next release.  Returning those tags to being generated fixes a lot of troubles for us.

**Comment by sembler** [comment]
@obecker did you plan on creating a PR for this, or should I work on it?

**Comment by obecker** [comment]
@sembler Here you are!

Fun fact: the manual `body` tag missed a lot of _onsomeevent_ attributes. Now with the generated code, this has been fixed as well.
