### ISSUE TITLE
j2html website

### ISSUE THREAD

**Issue by tipsy** [tipsy/j2html#189]
I'll see if I can get the website repo in shape so you guys can more easily make changes. Or maybe we should pull it in here?

**Comment by sembler** [comment]
I was going to suggest incorporating it into this repo.  The website examples would be much easier to keep in sync with the code changes if they were side-by-side.  I've also experimented with using Javascript to parse HTML and convert it into j2html syntax, and it would be a nice addition to the website when it is complete.

**Comment by tipsy** [comment]
Great, I'll see if I can get added. I gave it a quick makeover since I'm already messing around with it, let me know if you want me to make any other visual changes.

**Comment by tipsy** [comment]
This should be done now. Source code is in `website` and the built website is in `docs`. I'll write some READMEs.

**Comment by tipsy** [comment]
READMEs added. HTTPS not working properly, but might just take some time.

**Comment by tipsy** [comment]
>  I've also experimented with using Javascript to parse HTML and convert it into j2html syntax, and it would be a nice addition to the website when it is complete.

Nice, looking forward to seeing that!
