### ISSUE TITLE
Version 1.5.0 release 

### ISSUE THREAD

**Issue by tipsy** [tipsy/j2html#192]
TODO
- [x] Write release notes (`j2html/website`)
- [x] Render website HTML to `j2html/docs`
- [x] Update readme
- [ ] Post relevant places?

**Comment by bonndan** [comment]
Intellij suggested to upgrade to 1.5.0, which I tried. Unfortunately ContainerTag is now typed and this is a breaking change. Some release notes and an instruction how to upgrade would be nice.

**Comment by tipsy** [comment]
@bonndan I agree. I tried to hand over this project to someone else. In the beginning, it seemed like they were interested, but not much has happened lately. I am considering marking the project as abandoned.

**Comment by tipsy** [comment]
@sembler do you have any plans for the project?

**Comment by sembler** [comment]
Yes I have been using my spare time to experiment with parsing and code generation using Wattsi files.  There is good potential to use this to provide better type correctness and to keep current with the HTML specs.  

But I realize that this time spent has been at the expense of the more important tasks needed for maintaining this project.  So I'll change direction and focus on completing the tasks of this issue.  I expect to have an update by the 21st.

**Comment by tipsy** [comment]
Thanks @sembler, I was afraid you had left. It might be helpful to post in an issue every now and then to keep people posted :)

**Comment by sembler** [comment]
Release notes have been merged with #204 .  Ready for you to render and update the website @tipsy.

**Comment by tipsy** [comment]
@sembler I moved all of this into the repo last year. You can update the website by curling and committing. I wrote instructions in the readme ☺️

**Comment by sembler** [comment]
Whoops.  Indeed you did, and I completely forgot.

**Comment by sembler** [comment]
The website has been updated.  Did you have any specific places to post the news to @tipsy?

**Comment by bonndan** [comment]
Much better now 🎉

**Comment by tipsy** [comment]
> Did you have any specific places to post the news to @tipsy?

Not really, I will sometimes post releases to reddit.com/r/java, but usually not for small things (they get annoyed 😅)
