### ISSUE TITLE
Introduce API revision checks

### ISSUE THREAD

**Issue by sembler** [tipsy/j2html#194]
The release of version 1.5.0 revealed some accidental API changes that broke user code.  It was suggested that we incorporate [Revapi](https://revapi.org/) into our build process to compare against previous releases and discover any breaking changes.

**Comment by sembler** [comment]
@tipsy can we use the verify goal for actions for this project?  Or at least include the Revapi 'check' goal?

**Comment by sembler** [comment]
Looks like the goal change works as expected. I'll merge unless you have concerns @tipsy , @obecker.

**Comment by obecker** [comment]
Out of curiosity: what were those incompatible changes? Should we restore something?

**Comment by sembler** [comment]
https://github.com/tipsy/j2html/commit/26ba4c3cae3cd553927a1146e7f1e55669bc4b39

Basically the return types of TagCreator were no longer compatible with compiled libraries. I also noticed that some methods are gone, such as withRole() for ATags. I think we've gone past restoring things at this point. But we can at least ensure that this is more easily caught before merges.

**Comment by obecker** [comment]
Yes, probably 1.5.0 should have been 2.0.0.
The generated classes support only those attributes that are allowed per HTML specification, so many (wrongly used) attributes are gone, which is indeed no longer compatible.
