### ISSUE TITLE
[Question] How best to convert `Tag` for 1.5.0?

### ISSUE THREAD

**Issue by syntapy** [tipsy/j2html#207]
Hi, I am trying to upgrade a [codebase](https://github.com/seattle-uat/civiform/pull/2281) from 1.4.0 to 1.5.0

I understand I need to replace `ContainerTag` with specific subclasses like `DivTag` or `HtmlTag` since those inherit from `ContainerTag`

But when dealing with tags that aren't intended to have children (e.g. [here](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/views/BaseHtmlView.java#L40-L42)) I should do the same?

i.e. just use `H1Tag` in that line?

I can't find anything j2hmlt 1.5.0 that inherits directly from `Tag<T>`

**Comment by sembler** [comment]
Yes @syntapy , you'll want to use H1Tag as the return class.  The reasoning here is that some tags have specialized attributes, and by returning the specific class your IDE can inform you about the available attribute methods.  In this example you don't appear to need that, but consistency in your return types is recommended.
