### ISSUE TITLE
question for <code> tag

### ISSUE THREAD

**Issue by Suna-Wang** [tipsy/j2html#208]
I wrote a test case to test the code tag, the case is followed:

    public void pre_code_test12() {
        String output = pre(
            code("#include &lt;iostream&gt;" +
                "void main(){" +
                "cout &lt;&lt; &quot;Hello!&quot; &lt;&lt; end1;" +
                "}")
        ).render();
}
What I expected is
<pre><code>#include &lt;iostream&gt;void main(){cout &lt;&lt; &quot;Hello!&quot; &lt;&lt; end1;}</code></pre>
But the output is
<pre><code>#include &amp;lt;iostream&amp;gt;void main(){cout &amp;lt;&amp;lt; &amp;quot;Hello!&amp;quot; &amp;lt;&amp;lt; end1;}</code></pre>

Then the output will be different from the real need.
expected:
#include <iostream>void main(){cout << "Hello!" << end1;}
output:
#include &lt;iostream&gt;void main(){cout &lt;&lt; &quot;Hello!&quot; &lt;&lt; end1;}

How can I produce what I want?

**Comment by sembler** [comment]
@Suna-Wang j2html provides automatic text escaping in most cases.  For your example you can use:
`pre(
    code("#include <iostream>void main(){cout << "Hello!" << end1;}")
).render()`

which will produce this html:
`<pre><code>#include &lt;iostream&gt;void main(){cout &lt;&lt; &quot;Hello!&quot; &lt;&lt; end1;}</code></pre>`

which the browser should render into the output you desired.

**Comment by Suna-Wang** [comment]
> 

Thank you very much!~
