### ISSUE TITLE
Fail to create <generate> and <command> tag

### ISSUE THREAD

**Issue by Jie1466803079** [tipsy/j2html#209]
I'm using version 1.5.1 of j2html which is supposed to support the new tags of HTML5. However, I cannot create the <command> tag. Besides, there is a class named GenerateTag in the tags-specialized package, which means j2html should be allowed to create the <generate> tag. However, I cannot create this tag either. 

package j2html.tags.specialized;

import j2html.tags.ContainerTag;

public final class GenerateTag extends ContainerTag<GenerateTag> {
    public GenerateTag() {
        super("generate");
    }
}

**Comment by sembler** [comment]
@Jie1466803079 the `GenerateTag` is a mistake that slipped into commit acf6bff7.  It does not exist in the [HTML Standard](https://html.spec.whatwg.org/) and is planned for removal.

The `<command>` element is also not part of the standard.  It was only included in drafts, and I cannot find any browsers that support it.

If, for any reason, you need to create elements with these names you can use `TagCreator.tag(...)` and `TagCreator.emptyTag(...)` to create custom named elements.

**Comment by sembler** [comment]
Also, a follow up question.  Where did you find version 1.5.1?  We have not yet made a release with that version number.

**Comment by sembler** [comment]
The <generate> tag has been removed as of #211 .
