### ISSUE TITLE
Escaped text issues of "#" and "$%"

### ISSUE THREAD

**Issue by Jie1466803079** [tipsy/j2html#210]
There are several escaped texts in HTML. For example, the outputs of "#" and "$%" should be both "". However, I have found that those two texts cannot be escaped and the outputs are still "#" and "$%" respectively. Can anyone help with this? Thanks

**Comment by sembler** [comment]
Can you provide the context where you need to do this?  In most cases these characters do not need to be escaped because they do not conflict with HTML parsing rules.

If you want to do this you'll need to supply your own implementation of `TextEscaper` to `Config.withTextEscaper(...)`.
