### ISSUE TITLE
How to solve encoding problem

### ISSUE THREAD

**Issue by danieltoril** [tipsy/j2html#216]
Hello, I'm writing a page using your library, it's amazing. 
I'm migrating my jsp's to your library, but i've a problem with encoding.

meta().withCharset("UTF-8")
...
label("Configuración")
![encoding](https://user-images.githubusercontent.com/20238540/179161442-fcc61134-c525-4f5b-bf9d-11f80b134354.png)
If i change charset to ISO-8859-1 it works fine, but my original jsp page was working with UTF-8.
Thanks in advance!

**Comment by rayrobdod** [comment]
When calling `new java.io.FileWriter` (or `new java.io.OuputStreamWriter` or `java.nio.file.Files.newBufferedWriter`), the method has an optional `java.nio.charset.Charset` parameter, which has an unspecified default value but can be set to `java.nio.charset.StandardCharsets.UTF_8` to tell the writer to encode the characters using UTF-8. 

I don't think there is a straightforward way to use a explicit charset without specifying the charset independently in both the document's metadata and in the writer.

**Comment by danieltoril** [comment]
> When calling `new java.io.FileWriter` (or `new java.io.OuputStreamWriter` or `java.nio.file.Files.newBufferedWriter`), the method has an optional `java.nio.charset.Charset` parameter, which has an unspecified default value but can be set to `java.nio.charset.StandardCharsets.UTF_8` to tell the writer to encode the characters using UTF-8.
> 
> I don't think there is a straightforward way to use a explicit charset without specifying the charset independently in both the document's metadata and in the writer.

I'm render with HttpServletResponse.getWriter();

.render(FlatHtml.into(response.getWriter()))

How i can change the encoding of response writer?

**Comment by danieltoril** [comment]
I'm solved it, when adding:

response.setContentType("text/html");

previously to render to response
