### ISSUE TITLE
Calling render with io.Writer

### ISSUE THREAD

**Issue by abius** [tipsy/j2html#29]
I'm requesting a feature here, that is to have an method `render(java.io.Writer)`. When creating larger DOM's constructing a larger string might become a hassle, and if you plan to write the resulting string somewhere writing in a writer directly will be a lot faster. The best example of that would be the creation of an website, where creating the string for the whole DOM should be of magnitudes slower than writing it directly.
I suggest creating a method `render(java.lang.Appendable)` because this covers `Writer`s as well as `StringBuilder`.

**Comment by tipsy** [comment]
Could you create a PR for this?
