### ISSUE TITLE
Is there any option to format the generated html?

### ISSUE THREAD

**Issue by gaurs** [tipsy/j2html#32]
Hi,

I tried to use j2html in one of my projects. It is very fast and efficient, but the generated html code is not readable.

Is there any plan to add a format or beautify option to format/indent the generated tags for more readability?

**Comment by tipsy** [comment]
@gaurs pretty-printing is not within the scope of this project. Have you tried something like this: https://github.com/spullara/jtidy ?

**Comment by gaurs** [comment]
Thanks @tipsy ; Will take a look

**Comment by samodadela** [comment]
I found this is the easiest way to indent/format j2html output:
https://mkyong.com/java/java-pretty-print-html/

At least for debugging purposes.

**Comment by pointbazaar** [comment]
@gaurs  There is indeed an option to indent the generated code, with the ```.renderFormatted(int level)``` Method which is available on ```ContainerTag``` instances. 
https://github.com/tipsy/j2html/blob/master/library/src/main/java/j2html/tags/ContainerTag.java

**Comment by samodadela** [comment]
Yup, found that while looking at the source... I tried it but when comparing the generated output some elements were not indented correctly. It's good enough, though - I use indenting only when debugging.
