### ISSUE TITLE
create html to j2html converter

### ISSUE THREAD

**Issue by tipsy** [tipsy/j2html#4]

**Comment by snaketl** [comment]
Hi @tipsy!

First, I'd like to thank you for this project.
Is there something that i could help you in this feature?

Best regards!

**Comment by tipsy** [comment]
You're very welcome!

My plan was to create an editor where you could paste HTML, and get j2html-Java back. 

Basically the opposite of what you see here: http://domsel.github.io/. This is a JavaScript to HTML project I was working on (if you use uBlock adblock some scripts might be blocked).

So I need something that can parse HTML input and spit out j2html-java, preferably written in JavaScript :)

**Comment by tipsy** [comment]
Yeah, too much work.
