### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by davidbruce** [tipsy/j2html#41]
First off, this project is really cool!  Unfortunately, the documentation is a bit lacking and more examples would be nice.  

I plan on continuing to evaluate j2html and depending on how things go I will help out with the docs. 

A great reference for docs:
https://modules.ceylon-lang.org/repo/1/ceylon/html/1.2.2/module-doc/api/index.html

**Comment by tipsy** [comment]
Thanks fellow David!

The documentation could be more extensive, but the library just mimics HTML, so I figured there wasn't much point in writing out each method/tag. Could aways use more/better examples though. Is there anything in particular you found to be missing?

**Comment by davidbruce** [comment]
Hello Tipsy,

Sorry about taking so long to follow up.  After playing around with the library more and digging through its source it is extremely intuitive.  

I guess at this point more examples would be useful. I will try to think of some over the weekend and propose them here.

**Comment by tipsy** [comment]
@davidbruce any update?
