### ISSUE TITLE
Change unsafeHtml to safeHtml

### ISSUE THREAD

**Issue by danneu** [tipsy/j2html#44]
The purpose of `unsafeHtml` is that it does not escape the input which is only something you ever want to do when you know the html is **safe** since everything is otherwise escaped by default.

Currently, in j2html, `unsafeHtml("<h1>foo</h1>").render()` returns `"<h1>foo</h1>"`. This should really be called "safeHtml".

I'm guessing it's named "unsafeHtml" because that's what it produces. But other templating libraries I'm familiar with use the inverse `safe(markup)` including nunjucks (https://mozilla.github.io/nunjucks/templating.html#safe) and jinja, which makes more sense since you're basically annotating the text you're passing in as safe.

If you like the name `unsafeHtml` and don't like my proposal, I think `unescapedHtml` would still be a much less ambiguous name.

But I certainly would scratch my head if I saw `unsafeHtml(user.name)` in a project.

**Comment by tipsy** [comment]
Looking back at this now, the naming confuses me too. Safe/unsafe and unescaped/escaped are both ambiguous since you can't tell if that's what you're supposed to put in them or what they give back.

What about `htmlContent` as a name?

**Comment by danneu** [comment]
Maybe something just a bit less generic sounding (thus more noticeable when it shows up in a template) like a function with the word `raw` in it?

    div().with(
        h3(post.title),
        rawHtml(markdown(post.text))
    )

**Comment by tipsy** [comment]
`rawHtml` is perfect, thanks!
