### ISSUE TITLE
render() as pretty formatted string

### ISSUE THREAD

**Issue by leonsoft** [tipsy/j2html#47]
(1) render() as pretty formatted string   
an excample is here:  "**output**" section of  [https://github.com/jmurty/java-xmlbuilder](https://github.com/jmurty/java-xmlbuilder)

(2) method name is normally a verb or verb+noun. I renamed all methods **_withXxx_** to **_addXxx_**.  To me it's more friendly,

>     html().add(body().add(  
>         h1("Heading!").addClass("example"),  
>         a("asdfac").addHref("url"),  
>         br(),  
>         p().add(span("this is a line").addStyle("color:red").add(br()))      
>       )).render();

**Comment by tipsy** [comment]
This is outside the scope of the project, you can use another library for formatting.
