### ISSUE TITLE
Question Java7

### ISSUE THREAD

**Issue by chmuche** [tipsy/j2html#59]
The compatibility with java 7 should be maintained ?

**Comment by tipsy** [comment]
I think these are the only methods which require java8:

```
public static <T> DomContent each(Collection<T> collection, Function<? super T, DomContent> mapper) {
    return rawHtml(collection.stream().map(mapper.andThen(DomContent::render)).collect(Collectors.joining()));
}

public static <T> List<T> filter(Collection<T> collection, Predicate<? super T> filter) {
    return collection.stream().filter(filter).collect(Collectors.toList());
}
```
But I like them. Is there a way to keep them but make them unavailable for jdk<8 ?

**Comment by chmuche** [comment]
I love Java8 style, but I'm afraid it's impossible. Ifthis trick is possible, it's maybe complex and I don't know how to do it.

**Comment by chmuche** [comment]
I work on the HtmlRender know, but I see a way to do it I need to move this method to a another Class like DomContentUtils. and exclude this class of the jar only for java7 version.

To do this we need to migrate to gradle. and have 2 different Jar.
[A link maybe to follow](http://stackoverflow.com/questions/20008324/gradle-multiple-jars-from-single-source-folderl)

**Comment by tipsy** [comment]
Seems doable enough: https://spring.io/blog/2015/04/03/how-spring-achieves-compatibility-with-java-6-7-and-8#which-java-8-api-features-do-we-support

I'll have a look at it.

**Comment by tipsy** [comment]
I built the project using https://github.com/orfjackal/retrolambda and managed to run it in Java 7. I supposed adding checks for java1.8 should be easy enough.

**Comment by tipsy** [comment]
@chmuche Try building master now, should work down to verison6. If you call java7 methods you will get exceptions, but maybe that's okay?

**Comment by chmuche** [comment]
This can be a patch until Java9 multi release jar feature.
