### ISSUE TITLE
Why escape text by default?

### ISSUE THREAD

**Issue by metadeus** [tipsy/j2html#6]
```<a href="/">&#1043;&#1083;&#1072;&#1074;&#1085;&#1072;&#1103;</a>```

It's 2015 already, we have UTF-8!

**Comment by tipsy** [comment]
Mainly for security. Is it creating a problem for cyrillic script?
You can always use unsafeHtml() instead of text()?

**Comment by metadeus** [comment]
It's not a problem, but a space overhead or code boilerplate (a().unsafeHtml(&lt;text&gt;) instead of a(&lt;text&gt;)). It's enough to escape HTML entities only (like &amp;lt;, &amp;gt;, etc) for security reasons, isn't it?

**Comment by tipsy** [comment]
Yes, it should be enough. I lazily went with a simple implementation that escapes everything just to be safe.
I'll see if I can find a better implementation (or you can create a pull request!).

**Comment by metadeus** [comment]
I suggest ```apache.commons.lang3.StringEscapeUtils.escapeHtml4```.

**Comment by tipsy** [comment]
Fixed in 5ad63ad
