### ISSUE TITLE
Generated document just one line

### ISSUE THREAD

**Issue by svend06** [tipsy/j2html#65]
The html string generated with j2tml is written to a File using FileUtils.writeStringToFile(outputFile, html) just one longe line.

**Comment by tipsy** [comment]
Could you clarify what you mean here? j2html doesn't write anything to files.

**Comment by svend06** [comment]
I have following code:
`String html = html( ... head( ... body ( ... ))).render();
File outputfile = new File("outputfile.html");
FileUtils.writeStringToFile(outputfile, html);`

This results in a file "outputfile.html" where everything of the string html is just in one line.

**Comment by tipsy** [comment]
j2html doesn't pretty print HTML, you'd have to use a different library for that.

**Comment by rrbrandt** [comment]
1.  I love this.
2. Why not add it? Its the first thing I noticed too?  Can you format XML with another framework.... yes....
 BUT! (I love buts), why add another heavy handed frame work to a really cool light weight frame work?

**Comment by tipsy** [comment]
My thinking was that minified HTML is better in every way, since the output is going to be consumed by applications, not humans. If anyone writes a very small utility class for formatting, something like
`TagCreator.format(html)`, I will merge it.

**Comment by rrbrandt** [comment]
Point taken, you know what I will look into it. I have written pretty printers sense lisp/scheme. :-)

**Comment by Rendaw** [comment]
To add, all the examples show pretty printed html so I was surprised everything I generate is one line.  I need diffable html.  Even if a pretty printer doesn't materialize, making the example output slightly more representative of the output or providing some documentation (api reference?) that discusses the output would go a long way.

**Comment by tipsy** [comment]
> To add, all the examples show pretty printed html so I was surprised everything I generate is one line. I need diffable html for use with git. Even if a pretty printer doesn't materialize, making the example output slightly more representative of the actual output or providing some documentation (api reference?) that discusses the output would go a long way.

That's a good point. Have you had time to look into making a pretty-printer @rrbrandt?

**Comment by tipsy** [comment]
I'll have a go at it.

**Comment by tipsy** [comment]
Added a proposal in #72. It's very simple, and gives this output:

```text
                                          ->   <body>
body(                                     ->       <a>
    a("Some text"),                       ->           Some text
    div(                                  ->       </a>
        join("Some", b("bold"), "Text")   ->       <div>
    )                                     ->           Some <b>bold</b> Text
).renderFormatted()                       ->       </div>
                                          ->   </body>
```
Could add some special rules for tags that shouldn't newline, but it's probably not needed?

**Comment by tipsy** [comment]
@svend06 @rrbrandt @Rendaw ^^^

**Comment by Rendaw** [comment]
Wow, fast!  That looks great to me.  Pretty printing always changes the document in xml so I don't think you can be too picky about the details.

**Comment by tipsy** [comment]
1.2.0 (which includes this change) is available now

```
<dependency>
    <groupId>com.j2html</groupId>
    <artifactId>j2html</artifactId>
    <version>1.2.0</version>
</dependency>
```
