### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by paolop** [tipsy/j2html#67]
Hi,

just starting using the library and found that the first snippet of code of the section "Loops, each() and filter()" at https://j2html.com/examples.html does not compile. In particular:
```
body(
    div(attrs("#employees"),
        employees.stream().map(employee ->
            div(attrs(".employee"),
                h2(employee.getName()),
                img().withSrc(employee.getImgPath()),
                p(employee.getTitle())
            )
        ).collect(Collectors.toList())
    )
)

```

should be something like:
```
body(
    div(attrs("#employees"),
        employees.stream().map(employee ->
            div(attrs(".employee"),
                h2(employee.getName()),
                img().withSrc(employee.getImgPath()),
                p(employee.getTitle())
            )
        ).toArray(ContainerTag[]::new)
    )
)
```
The problem is `.collect(Collectors.toList())`
given that the div method accepts a vararg of type ContainerTag that derives from DomContent. Isn't?

Paolo

**Comment by tipsy** [comment]
I might have update the library without updating the example, I'll have a look after work today.

**Comment by tipsy** [comment]
Thanks @paolop, the website has been updated: https://j2html.com/examples.html#loops

Can I ask why you decided to use `stream()` instead of `TagCreator.each()`?

**Comment by paolop** [comment]
@tipsy just for laziness :) I just started playing with the library a few hours ago and at the moment I feel more comfortable with Java streams. Thx.
