### ISSUE TITLE
Make text escaping configurable

### ISSUE THREAD

**Issue by sbezkostnyi** [tipsy/j2html#68]
Hi,
Is it possible to make text escaping configurable?
Let's say I want to use different implementation of text escaping or disable it completely.

I think it should be possible to achieve using [ServiceLoader](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html).
I can provide pull request if you are interested.

**Comment by tipsy** [comment]
There is the `TagCreator.rawHtml()` method for unescaped text, will using that solve your problem?

**Comment by sbezkostnyi** [comment]
Well, in case I don't need escaping completely, I'll need to use this method everywhere. It'll create unnecessary noise in code.

**Comment by tipsy** [comment]
`rawHtml()` is only 3 letters longer than `text()`. How do you propose it should be configurable? Why do you need it everywhere? Can you show me an example of the kind of code you're writing?

**Comment by sbezkostnyi** [comment]
Only if you are going to create `Text` element directly, but if you are use `withText()` method you need to wrap input in `rawHtml()`.

For example instead of writing `span.withText()` I need to write `span.with(rawHtml())`. It's longer and adds additional parentheses.

For proposed solution please take a look at #69.

**Comment by sbezkostnyi** [comment]
Implemented in #70.
