### ISSUE TITLE
Add methods to add title attribute

### ISSUE THREAD

**Issue by sbezkostnyi** [tipsy/j2html#71]
Hello,
I found myself writing a lot of `tag.attr("title", title)` code and I thought it may be a good idea to add `withTitle`/`withCondTitle` methods to `Tag` class. What do you think?

**Comment by tipsy** [comment]
Sounds good. If you make a PR, I'll merge it.

**Comment by tipsy** [comment]
1.2.0 (which includes this change) is available now

```
<dependency>
    <groupId>com.j2html</groupId>
    <artifactId>j2html</artifactId>
    <version>1.2.0</version>
</dependency>
```

**Comment by sbezkostnyi** [comment]
Thanks. And for other features in 1.2.0 too.
