### ISSUE TITLE
rawHtml with <null> throws Exception

### ISSUE THREAD

**Issue by kicktipp** [tipsy/j2html#78]
I am using j2html just for a few days, so I don't know if it is a bug or a feature:

Using this code:
`rawHtml(iff(condition, "<p>Hallo</p>"))`

boils down to `rawHtml(null)`

This gives an error at least with my [PrintWriter](https://github.com/spring-projects/spring-security/blob/f2ccc53549c8b5235ceb105166e8f4b714212f3c/web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java#L473) from Spring Security as it checks the length of the CharSequence which fails with a NPE.

Wouldn't it be better something like this:

```
public static DomContent iff ( boolean condition, DomContent ifValue ) {
	return condition ? ifValue : new NullDomContent();
}

public class NullDomContent extends DomContent {
	@Override
	public String render ( ) { return ""; }
}
```
No null check is needed. This could be used in ContainerTag, too: 
```
if (child == null) {
           return this; // in some cases, like when using iff(), we ignore null children
}
```

**Comment by tipsy** [comment]
Sounds reasonable. Want to create a PR?

**Comment by kicktipp** [comment]
I am not sure if this is a good decision. The iff method takes plain Strings as well. Take a look at 
https://github.com/kicktipp/j2html/tree/j2-html-78
and decide yourself if you want to merge

The null check in ContainerTag can not be removed because of backwards compatibility
