### ISSUE TITLE
mvn install : Failure

### ISSUE THREAD

**Issue by ronanlg** [tipsy/j2html#8]
When I'm doing a "mvn install", I got a Failure in the tests on the "j2html.tags.TagCreatorTest" test.
Running the project with java 8 (oracle) or java 7(open jdk), maven 3.0.5  under linux (Ubuntu 14.04). 
Following message in target/surfire-reports/j2html.tags.TagCreatorTest.txt : 
org.junit.ComparisonFailure: expected:<<body>[
    Any content
</body>]
> but was:<<body>[
    Any content
]/body>
>

**Comment by tipsy** [comment]
Did your EOL PR fix this?
